easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\RealCurrency
       - App\Entity\CryptoCurrency
#        - App\Entity\Category
#        - App\Entity\User
